### ISSUE TITLE
Pytorch version?

### ISSUE THREAD

**Issue by WCZ93762** [prs-eth/thera#1]
Hello, thank you very much for your excellent work. The paper mentions there is a PyTorch version of Thera. Will it be released?

**Comment by alebeck** [comment]
Hi, thanks for your interest in our work! The main codebase is written with JAX, and we do not plan to release a PyTorch version of that. However, we are planning to upload PyTorch code for fitting a single Thera field to an image (i.e., without the super-resolution parts), as mentioned in the paper. This could take some more time though.
Best, Alex
